services:
  - type: web
    name: realtime-whiteboard-ot
    runtime: node
    plan: free
    buildCommand: npm run postinstall && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: HOST
        value: 0.0.0.0
      - key: MONGODB_URI
        sync: false
